#!/bin/bash
#set -x
pom="$(dirname $(readlink -f $0))/pom.xml"
args=(${@// /\\ })
exec mvn --batch-mode --quiet \
    --file "$pom" \
    exec:java -Dexec.mainClass=dk.ange.stowbase.parse.XlsVesselToJson -Dexec.args="${args[*]}"
